[package]
name = "picturium-libvips"
description = "Libvips bindings for picturium media server"
license = "GPL-3.0-only"
version = "0.1.4"
edition = "2024"
exclude = ["data/*"]

[build-dependencies]
bindgen = "0.72.0"

[dependencies]
bitmask-enum = "2.2.5"
