FROM ubuntu:24.04

COPY --from=lamka02sk/picturium-base:8.17.1 /usr/local/lib /usr/local/lib
COPY --from=lamka02sk/picturium-base:8.17.1 /usr/local/bin/vips /usr/local/bin/vips
COPY --from=lamka02sk/picturium-base:8.17.1 /lib/x86_64-linux-gnu /lib/x86_64-linux-gnu
COPY --from=lamka02sk/picturium-base:8.17.1 /lib/aarch64-linux-gnu /lib/aarch64-linux-gnu
COPY --from=lamka02sk/picturium-base:8.17.1 /usr/lib/libreoffice /usr/lib/libreoffice
COPY --from=lamka02sk/picturium-base:8.17.1 /usr/share/libreoffice /usr/share/libreoffice
COPY --from=lamka02sk/picturium-base:8.17.1 /usr/share/liblangtag /usr/share/liblangtag
COPY --from=lamka02sk/picturium-base:8.17.1 /usr/share/color /usr/share/color
COPY --from=lamka02sk/picturium-base:8.17.1 /usr/share/ghostscript /usr/share/ghostscript
COPY --from=lamka02sk/picturium-base:8.17.1 /usr/share/poppler /usr/share/poppler
COPY --from=lamka02sk/picturium-base:8.17.1 /usr/share/mime /usr/share/mime
COPY --from=lamka02sk/picturium-base:8.17.1 /etc /etc

RUN apt update -y && apt install -y curl gcc && apt autoremove && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/usr/lib/libreoffice/program:/root/.cargo/bin:${PATH}"
RUN cargo install cargo-watch

RUN mkdir /root/picturium-libvips && ldconfig

WORKDIR /root/picturium-libvips
